// <auto-generated />
using System;
using AuthDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190131090929_sp")]
    partial class sp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthDemo.Models.AccountDetail", b =>
                {
                    b.Property<int>("AccountDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountDetailId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerAccountId");

                    b.Property<int>("DayOfWeekNumber");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("EndTimeInMinutes")
                        .HasColumnName("EndTimeInMinutes")
                        .HasColumnType("time");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVisible")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("StartTimeInMinutes")
                        .HasColumnName("StartTimeInMinutes")
                        .HasColumnType("time");

                    b.HasKey("AccountDetailId")
                        .HasName("PrimaryKey_AccountDetailId");

                    b.HasIndex("CustomerAccountId");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("AuthDemo.Models.AccountRate", b =>
                {
                    b.Property<int>("AccountRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AccountRateId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerAccountId");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnName("RatePerHour")
                        .HasColumnType("DECIMAL(6,2)");

                    b.HasKey("AccountRateId")
                        .HasName("PrimaryKey_AccountRateId");

                    b.HasIndex("CustomerAccountId");

                    b.ToTable("AccountRates");
                });

            modelBuilder.Entity("AuthDemo.Models.CustomerAccount", b =>
                {
                    b.Property<int>("CustomerAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerAccountId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnName("AccountName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Comments")
                        .HasColumnName("Comments")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("CreatedById");

                    b.Property<bool>("IsVisible")
                        .HasColumnName("IsVisible")
                        .HasColumnType("BIT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("UpdatedById");

                    b.HasKey("CustomerAccountId")
                        .HasName("PrimaryKey_CustomerAccountId");

                    b.HasIndex("AccountName")
                        .IsUnique()
                        .HasName("CustomerAccount_AccountName_UniqueConstraint");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("AuthDemo.Models.InstructorAccount", b =>
                {
                    b.Property<int>("InstructorAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("InstructorAccountId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnName("Comments")
                        .HasColumnType("NVARCHAR(4000)");

                    b.Property<int>("CustomerAccountId")
                        .HasColumnName("CustomerAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<int>("InstructorId")
                        .HasColumnName("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsCurrent")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("WageRate")
                        .HasColumnName("WageRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("InstructorAccountId")
                        .HasName("PrimaryKey_InstructorAccounttId");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorAccounts");
                });

            modelBuilder.Entity("AuthDemo.Models.SessionSynopsis", b =>
                {
                    b.Property<int>("SessionSynopsisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SessionSynopsisId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedById");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsVisible")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SessionSynopsisName")
                        .IsRequired()
                        .HasColumnName("SessionSynopsisName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("UpdatedById");

                    b.HasKey("SessionSynopsisId")
                        .HasName("PrimaryKey_SessionSynopsisId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SessionSynopsisName")
                        .IsUnique()
                        .HasName("SessionSynopsis_SessionSynopsisName_UniqueConstraint");

                    b.HasIndex("UpdatedById");

                    b.ToTable("SessionSynopses");
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ApprovedAt");

                    b.Property<int?>("ApprovedById")
                        .IsRequired();

                    b.Property<int>("CheckedById");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("CreatedById");

                    b.Property<int>("InstructorId");

                    b.Property<DateTime>("MonthAndYear")
                        .HasColumnName("MonthAndYear");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnName("RatePerHour")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("UpdatedById")
                        .HasColumnName("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAndSubmittedAt")
                        .HasColumnName("VerifiedAndSubmittedAt");

                    b.HasKey("TimeSheetId")
                        .HasName("PrimaryKey_TimeSheetId");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InstructorId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheetDetail", b =>
                {
                    b.Property<int>("TimeSheetDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetDetailId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountDetailId");

                    b.Property<DateTime>("DateOfLesson");

                    b.Property<bool>("IsReplacementInstructor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsReplacementInstructor")
                        .HasDefaultValue(false);

                    b.Property<int>("OfficialTimeInMinutes")
                        .HasColumnName("OfficialTimeInMinutes");

                    b.Property<int>("OfficialTimeOutMinutes")
                        .HasColumnName("OfficialTimeOutMinutes");

                    b.Property<string>("SessionSynopsisNames")
                        .IsRequired()
                        .HasColumnName("SessionSynopsisNames")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<int>("TimeInInMinutes");

                    b.Property<int>("TimeOutInMinutes");

                    b.Property<int>("TimeSheetId");

                    b.Property<decimal>("WageRatePerHour")
                        .HasColumnName("WageRatePerHour")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("TimeSheetDetailId")
                        .HasName("PrimaryKey_TimeSheetDetailId");

                    b.HasIndex("AccountDetailId");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("TimeSheetDetails");
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheetDetailSignature", b =>
                {
                    b.Property<int>("TimeSheetDetailSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TimeSheetDetailSignatureId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Signature")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<int>("TimeSheetIDetailId");

                    b.HasKey("TimeSheetDetailSignatureId")
                        .HasName("PrimaryKey_TimeSheetSignatureId");

                    b.HasIndex("TimeSheetIDetailId")
                        .IsUnique();

                    b.ToTable("TimeSheetDetailSignature");
                });

            modelBuilder.Entity("AuthDemo.Models.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserInfoId")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LoginUserName")
                        .IsRequired()
                        .HasColumnName("LoginUserName")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnName("PasswordHash")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnName("PasswordSalt")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnName("Role")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("UserInfoId")
                        .HasName("PrimaryKey_UserInfoId");

                    b.HasIndex("LoginUserName")
                        .IsUnique()
                        .HasName("UserInfo_LoginUserName_UniqueConstraint");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new { UserInfoId = 1, Email = "KENNY@FAIRYSCHOOL.COM", FullName = "KENNY", IsActive = true, LoginUserName = "88881", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Admin" },
                        new { UserInfoId = 2, Email = "JULIET@FAIRYSCHOOL.COM", FullName = "JULIET", IsActive = true, LoginUserName = "88882", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Admin" },
                        new { UserInfoId = 3, Email = "RANDY@HOTINSTRUCTOR.COM", FullName = "RANDY", IsActive = true, LoginUserName = "88883", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Instructor" },
                        new { UserInfoId = 4, Email = "THOMAS@HOTINSTRUCTOR.COM", FullName = "THOMAS", IsActive = true, LoginUserName = "88884", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Instructor" },
                        new { UserInfoId = 5, Email = "BEN@HOTINSTRUCTOR.COM", FullName = "BEN", IsActive = true, LoginUserName = "88885", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Instructor" },
                        new { UserInfoId = 6, Email = "GABRIEL@HOTINSTRUCTOR.COM", FullName = "GABRIEL", IsActive = true, LoginUserName = "88886", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Instructor" },
                        new { UserInfoId = 7, Email = "FRED@HOTINSTRUCTOR.COM", FullName = "FRED", IsActive = true, LoginUserName = "88887", PasswordHash = new byte[] { 174, 78, 52, 254, 15, 96, 176, 128, 105, 168, 54, 131, 172, 210, 223, 136, 188, 155, 103, 74, 228, 24, 174, 208, 99, 67, 95, 162, 50, 225, 253, 239, 119, 232, 166, 57, 46, 183, 200, 44, 58, 174, 247, 16, 92, 249, 194, 152, 114, 238, 53, 58, 242, 152, 66, 0, 90, 103, 85, 177, 170, 132, 15, 93 }, PasswordSalt = new byte[] { 17, 221, 108, 57, 94, 221, 64, 146, 41, 228, 131, 144, 81, 49, 180, 25, 25, 149, 126, 83, 92, 120, 197, 154, 159, 87, 234, 144, 154, 74, 122, 66, 98, 97, 126, 99, 226, 52, 199, 43, 78, 154, 1, 247, 216, 105, 224, 122, 118, 51, 90, 126, 128, 50, 123, 61, 109, 87, 107, 16, 32, 143, 108, 69, 148, 162, 91, 242, 62, 66, 199, 245, 168, 83, 104, 239, 245, 198, 73, 163, 173, 207, 194, 131, 66, 191, 236, 253, 69, 106, 108, 173, 198, 164, 146, 87, 85, 50, 79, 81, 146, 99, 251, 233, 231, 158, 243, 166, 75, 3, 129, 113, 32, 1, 103, 89, 31, 194, 7, 158, 17, 101, 191, 105, 131, 83, 181, 196 }, Role = "Instructor" }
                    );
                });

            modelBuilder.Entity("AuthDemo.Models.AccountDetail", b =>
                {
                    b.HasOne("AuthDemo.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("AccountDetails")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuthDemo.Models.AccountRate", b =>
                {
                    b.HasOne("AuthDemo.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("AccountRates")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuthDemo.Models.CustomerAccount", b =>
                {
                    b.HasOne("AuthDemo.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthDemo.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AuthDemo.Models.InstructorAccount", b =>
                {
                    b.HasOne("AuthDemo.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("InstructorAccounts")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AuthDemo.Models.UserInfo", "Instructor")
                        .WithMany("InstructorAccounts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuthDemo.Models.SessionSynopsis", b =>
                {
                    b.HasOne("AuthDemo.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthDemo.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheet", b =>
                {
                    b.HasOne("AuthDemo.Models.UserInfo", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthDemo.Models.UserInfo", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthDemo.Models.UserInfo", "Instructor")
                        .WithMany("TimeSheets")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AuthDemo.Models.UserInfo", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheetDetail", b =>
                {
                    b.HasOne("AuthDemo.Models.AccountDetail", "AccountDetail")
                        .WithMany("TimeSheetDetails")
                        .HasForeignKey("AccountDetailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AuthDemo.Models.TimeSheet", "TimeSheet")
                        .WithMany("TimeSheetDetails")
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuthDemo.Models.TimeSheetDetailSignature", b =>
                {
                    b.HasOne("AuthDemo.Models.TimeSheetDetail", "TimeSheetDetail")
                        .WithOne("TimeSheetDetailSignature")
                        .HasForeignKey("AuthDemo.Models.TimeSheetDetailSignature", "TimeSheetIDetailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
